stages:
  data-preprocessing-flats:
    cmd: python .\src\data\data-preprocessing-flats.py .\data\raw\flats.csv
    deps:
    - .\src\data\data-preprocessing-flats.py
    - .\data\raw\flats.csv

  data-preprocessing-houses:
    cmd: python .\src\data\data-preprocessing-houses.py .\data\raw\houses.csv
    deps:
    - .\src\data\data-preprocessing-houses.py
    - .\data\raw\houses.csv

  merge-flats-and-houses:
    cmd: python .\src\data\merge-flats-and-houses.py .\data\processed\flats_cleaned.csv .\data\processed\house_cleaned.csv
    deps:
    - .\src\data\merge-flats-and-houses.py
    - .\data\processed\flats_cleaned.csv
    - .\data\processed\house_cleaned.csv

  data-preprocessing-level-2:
    cmd: python .\src\data\data-preprocessing-level-2.py .\data\processed\gurgaon_properties.csv
    deps:
    - .\src\data\data-preprocessing-level-2.py
    - .\data\processed\gurgaon_properties.csv

  feature-engineering:
    cmd: python .\src\features\feature-engineering.py .\data\processed\gurgaon_properties_cleaned_v1.csv .\data\raw\appartments.csv
    deps:
    - .\src\features\feature-engineering.py
    - .\data\processed\gurgaon_properties_cleaned_v1.csv
    - .\data\raw\appartments.csv

  outlier-treatment:
    cmd: python .\src\features\outlier-treatment.py .\data\processed\gurgaon_properties_cleaned_v2.csv
    deps:
    - .\src\features\outlier-treatment.py
    - .\data\processed\gurgaon_properties_cleaned_v2.csv

  missing_value_imputation:
    cmd: python .\src\features\missing-value-imputation.py .\data\processed\gurgaon_properties_outlier_treated.csv
    deps:
    - .\src\features\missing-value-imputation.py
    - .\data\processed\gurgaon_properties_outlier_treated.csv

  feature-selection:
    cmd: python .\src\features\feature-selection.py .\data\processed\gurgaon_properties_missing_value_imputation.csv
    deps:
    - .\src\features\feature-selection.py
    - .\data\processed\gurgaon_properties_missing_value_imputation.csv

  make_dataset:
    cmd: python .\src\data\make_dataset.py .\data\processed\gurgaon_properties_post_feature_selection.csv
    deps: 
    - .\src\data\make_dataset.py 
    - .\data\processed\gurgaon_properties_post_feature_selection.csv

  train_model:
    cmd: python .\src\models\train_model.py .\data\processed\train.csv
    deps:
    - .\src\models\train_model.py
    - .\data\processed\train.csv