stages:
  data-preprocessing-flats:
    cmd: python .\src\data\data-preprocessing-flats.py .\data\raw\flats.csv
    deps:
    - .\src\data\data-preprocessing-flats.py
    - .\data\raw\flats.csv

  data-preprocessing-houses:
    cmd: python .\src\data\data-preprocessing-houses.py .\data\raw\houses.csv
    deps:
    - .\src\data\data-preprocessing-houses.py
    - .\data\raw\houses.csv

  merge-flats-and-houses:
    cmd: python .\src\data\merge-flats-and-houses.py .\data\processed\flats_cleaned.csv .\data\processed\house_cleaned.csv
    deps:
    - .\src\data\merge-flats-and-houses.py
    - .\data\processed\flats_cleaned.csv
    - .\data\processed\house_cleaned.csv
