stages:
  data-preprocessing-flats:
    cmd: python .\src\data\data-preprocessing-flats.py
    deps:
    - .\src\data\data-preprocessing-flats.py

  data-preprocessing-houses:
    cmd: python .\src\data\data-preprocessing-houses.py
    deps:
    - .\src\data\data-preprocessing-houses.py

  merge-flats-and-houses:
    cmd: python .\src\data\merge-flats-and-houses.py  
    deps:
    - .\src\data\merge-flats-and-houses.py

  data-preprocessing-level-2:
    cmd: python .\src\data\data-preprocessing-level-2.py 
    deps:
    - .\src\data\data-preprocessing-level-2.py

  feature-engineering:
    cmd: python .\src\features\feature-engineering.py
    deps:
    - .\src\features\feature-engineering.py

  outlier-treatment:
    cmd: python .\src\features\outlier-treatment.py
    deps:
    - .\src\features\outlier-treatment.py

  missing_value_imputation:
    cmd: python .\src\features\missing-value-imputation.py 
    deps:
    - .\src\features\missing-value-imputation.py

  feature-selection:
    cmd: python .\src\features\feature-selection.py 
    deps:
    - .\src\features\feature-selection.py

  make_dataset:
    cmd: python .\src\data\make_dataset.py
    deps: 
    - .\src\data\make_dataset.py 

  train_model:
    cmd: python .\src\models\train_model.py
    deps:
    - .\src\models\train_model.py

  data_visualization:
    cmd: python .\src\data\data_visualization.py
    deps:
    - .\src\data\data_visualization.py

  recommender-system:
    cmd: python .\src\features\recommender-system.py
    deps:
    - .\src\features\recommender-system.py

  streamlit:
    cmd: streamlit run Home.py 
    deps:
    - .\Home.py
    - .\pages\1_Price Predictor.py
    - .\pages\2_Analysis App.py
    - .\pages\3_Recommend Appartments.py