s3:
  aws_access_key_id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  aws_secret_access_key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  region_name: 'us-east-2'
  bucket: 'real-estate-data-project'
  raw_data_key: data/raw/your_data.csv
  processed_data_key: data/processed/flats_cleaned.csv
data-preprocessing-flats:
  input_data: 'data/raw/flats.csv'
  output_data: 'data/processed/flats_cleaned.csv'
data-preprocessing-houses:
  input_data: 'data/raw/houses.csv'
  output_data: 'data/processed/house_cleaned.csv'
merge-flats-and-houses:
  input_data1: 'data/processed/flats_cleaned.csv'
  input_data2: 'data/processed/house_cleaned.csv'
  output_data: 'data/processed/gurgaon_properties.csv'
data-preprocessing-level-2:
  input_data: 'data/processed/gurgaon_properties.csv'
  output_data: 'data/processed/gurgaon_properties_cleaned_v1.csv'
feature-engineering:
  input_data1: 'data/processed/gurgaon_properties_cleaned_v1.csv'
  input_data2: 'data/raw/appartments.csv'
  output_data: 'data/processed/gurgaon_properties_cleaned_v2.csv'
outlier-treatment:
  input_data: 'data/processed/gurgaon_properties_cleaned_v2.csv'
  output_data: 'data/processed/gurgaon_properties_outlier_treated.csv'
missing_value_imputation:
  input_data: 'data/processed/gurgaon_properties_outlier_treated.csv'
  output_data: 'data/processed/gurgaon_properties_missing_value_imputation.csv'
feature-selection:
  input_data: 'data/processed/gurgaon_properties_missing_value_imputation.csv'
  output_data: 'data/processed/gurgaon_properties_post_feature_selection.csv'
make_dataset:
  input_data: 'data/processed/gurgaon_properties_post_feature_selection.csv'
  output_data1: 'data/processed/train.csv'
  output_data2: 'data/processed/test.csv'
  test_split: 0.2
  seed: 2023
train_model:
  input_data: 'data/processed/train.csv'
  output_data: 'models/trained_model.pkl'
data_visualization:
  input_data1: 'data/processed/latlong.csv'
  input_data2: 'data/processed/gurgaon_properties_missing_value_imputation.csv'
  input_data3: 'data/processed/gurgaon_properties.csv'
  output_data:  'data/processed/data_viz1.csv'
  output_model: 'models/feature_text.pkl'
recommender-system:
  input_data: 'data/raw/appartments.csv'
  cosine_sim1_model: 'models/cosine_sim1.pkl'
  cosine_sim2_model: 'models/cosine_sim2.pkl'
  cosine_sim3_model: 'models/cosine_sim3.pkl'
  location_dataframe: 'models/locations_df.pkl'
run-streamlit:
  price_predictor_data: 'data/processed/gurgaon_properties_post_feature_selection.csv'
  train_model: 'models/trained_model.pkl'
  analytics_data: 'data/processed/data_viz1.csv'
  analytics_model_data: 'models/feature_text.pkl'