name: CI Pipeline  # Define the name of the GitHub Actions workflow

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the master branch

jobs:
  build:  # Define a job named 'build' for installing Python
    name: Install Python  # Specify a name for the job
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout Repository  # Checkout the repository's code
      uses: actions/checkout@v3

    - name: Set up Python  # Set up Python on the runner
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"  # Specify the Python version

    - name: Install Dependencies  # Install project dependencies
      run: |
        python -m pip install --upgrade pip

  docker:  # Define a job named 'docker' for building and pushing Docker images
    name: Build and push Docker images  # Specify a name for the job
    needs: build  # Depend on the completion of the 'build' job
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
      - name: Set up QEMU  # Set up QEMU for cross-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx  # Set up Docker Buildx for multi-platform builds
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub  # Log in to Docker Hub with credentials
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Use Docker Hub username from secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Use Docker Hub password from secrets

      - name: Build and push  # Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          push: true  # Push the Docker image
          tags: user/app:latest  # Specify the Docker image tags
