name: CI Pipeline

on:
  push:
    branches:
      - main  # Adjust this to your main branch name if it's different

jobs:
  Build:
    name: Continuous Integration
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.7  # Adjust this to your Python version if needed

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run DVC Repro
      run: dvc repro

    - name: Display Success Message
      if: success()
      run: echo "All pipelines executed successfully!"

    # Add more steps for your CI process as needed
